name: Repository Dispatch

on:
  repository_dispatch:
    types: [updates]

jobs:
  build:
  
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v3
    - uses: yunwei37/OpenAI-Continuous-Translator@master
      with:
          git_repo_url: https://github.com/christian-qt/Space-test
          api_key: ${{ secrets.API_KEY }}
          file_types: "md"
          target_language: Japanese
    - name: Add & Commit
      uses: EndBug/add-and-commit@v9.1.1
